name: '[builder] CI for releases'

on:
    push:
        branches:
            - dev

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ neko.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ neko.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
            with:
                version: latest
        -
            name: Build base dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file .m1k1o/base/Dockerfile.arm . \
                --tag $(echo "${DOCKER_USERNAME}")/neko:arm-base
        -
            name: Build chromium dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file .m1k1o/chromium/Dockerfile.arm . \
                --tag $(echo "${DOCKER_USERNAME}")/neko:arm-chromium
        -
            name: Build firefox dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file .m1k1o/firefox/Dockerfile.arm . \
                --tag $(echo "${DOCKER_USERNAME}")/neko:arm-firefox



