name: '[builder] CI for releases'

on:
    push:
        branches:
            - github-actions

jobs:
    release_base:
        runs-on: self-hosted
        if: github.repository_owner == 'mbattista'
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
          - name: Build base dockerfile (with push)
            run: |
                cd .m1k1o; \
                sed -i 's/m1k1o/mbattista/g' .env.default; \
                ./build arm-base; \
                docker push mbattista/neko:arm-base

    release:
        runs-on: self-hosted
        if: github.repository_owner == 'mbattista'
        needs: [ release_base ]
        strategy:
          matrix:
            tags: [firefox, chromium, google-chrome, ungoogled-chromium, tor-browser, vncviewer, vlc, xfce]
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Dockerhub login
          env:
              DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          run: |
              echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        - name: Build tags
          run: |
            .m1k1o/build ${DOCKER_TAG}
            docker push mbattista/neko:pi3-${DOCKER_TAG}
          env:
            DOCKER_TAG: ${{ matrix.tags }}

