name: '[builder] CI for releases'

on:
    push:
        branches:
            - dev

jobs:
    release:
        runs-on: self-hosted
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Build base dockerfile (with push)
            run: |
                docker build \
                --file .m1k1o/base/Dockerfile.arm .m1k1o/base \
                --platform "linux/arm/v7" \
                --tag mbattista/neko:arm-base; \
                docker push mbattista/neko:arm-base
        -
            name: Build chromium dockerfile (with push)
            run: |
                docker build \
                --file .m1k1o/chromium/Dockerfile.arm .m1k1o/chromium \
                --build-arg="BASE_IMAGE=mbattista/neko:arm-base" \
                --platform "linux/arm/v7" \
                --tag mbattista/neko:arm-chromium; \
                docker push mbattista/neko:arm-chromium
        -
            name: Build firefox dockerfile (with push)
            run: |
                docker build \
                --file .m1k1o/firefox/Dockerfile.arm . \
                --build-arg="BASE_IMAGE=mbattista/neko:arm-base"
                --tag mbattista/neko:arm-firefox; \
                docker push mbattista/neko:arm-firefox



