name: '[builder] CI for releases'

on:
    push:
        branches:
            - arm-build

jobs:
    release:
        runs-on: self-hosted
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Build base dockerfile (with push)
            run: |
                cd .m1k1o; \
                sed -i 's/m1k1o/mbattista/g' .env.default; \
                ./build arm-base; \
                docker push mbattista/neko:arm-base
        -
            name: Build chromium dockerfile (with push)
            run: |
                cd .m1k1o; \
                sed -i 's/m1k1o/mbattista/g' .env.default; \
                ./build arm-chromium; \
                docker push mbattista/neko:arm-chromium
        -
            name: Build firefox dockerfile (with push)
            run: |
                cd .m1k1o; \
                sed -i 's/m1k1o/mbattista/g' .env.default; \
                ./build arm-firefox; \
                docker push mbattista/neko:arm-firefox

